version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html

hooks:
  BeforeInstall:
    - location: scripts/nginx_install.sh
      timeout: 300
      runas: root
    - location: scripts/nginx_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/nginx_stop.sh
      timeout: 300
      runas: root