version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update -y
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /var/www/html/  # Ensure the directory exists
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - sudo nginx -s reload || sudo nginx  # Reload NGINX, or start if not running

artifacts:
  files:
    - /var/www/html/index.html

