version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx"
      - yum update -y
      - yum install nginx -y
      - echo "Creating directory if it does not exist"
      - mkdir -p /var/www/html

  build:
    commands:
      - echo "Copying index.html to Nginx directory"
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Starting Nginx"
      - systemctl start nginx || { echo "Failed to start Nginx"; exit 1; }
